/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {12, 1, 0, 9, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* mav_nmpc_tracker_model_expl_vde_adj:(i0[9],i1[9],i2[3],i3[])->(o0[12x1,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55;
  /* #0: @0 = 0.005 */
  w0 = 5.0000000000000001e-03;
  /* #1: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = input[0][8] */
  w3 = arg[0] ? arg[0][8] : 0;
  /* #4: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #5: @5 = (@2*@4) */
  w5  = (w2*w4);
  /* #6: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #7: @6 = input[2][2] */
  w6 = arg[2] ? arg[2][2] : 0;
  /* #8: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #9: @8 = input[1][0] */
  casadi_copy(arg[1], 9, w8);
  /* #10: {@9, @10, @11, @12, @13, @14, @15, @16, NULL} = vertsplit(@8) */
  w9 = w8[0];
  w10 = w8[1];
  w11 = w8[2];
  w12 = w8[3];
  w13 = w8[4];
  w14 = w8[5];
  w15 = w8[6];
  w16 = w8[7];
  /* #11: @7 = (@7*@12) */
  w7 *= w12;
  /* #12: @7 = (-@7) */
  w7 = (- w7 );
  /* #13: @17 = 0.005 */
  w17 = 5.0000000000000001e-03;
  /* #14: @18 = input[0][6] */
  w18 = arg[0] ? arg[0][6] : 0;
  /* #15: @19 = cos(@18) */
  w19 = cos( w18 );
  /* #16: @20 = sin(@3) */
  w20 = sin( w3 );
  /* #17: @21 = (@19*@20) */
  w21  = (w19*w20);
  /* #18: @22 = cos(@3) */
  w22 = cos( w3 );
  /* #19: @23 = sin(@1) */
  w23 = sin( w1 );
  /* #20: @24 = (@22*@23) */
  w24  = (w22*w23);
  /* #21: @25 = sin(@18) */
  w25 = sin( w18 );
  /* #22: @26 = (@24*@25) */
  w26  = (w24*w25);
  /* #23: @21 = (@21-@26) */
  w21 -= w26;
  /* #24: @21 = (@17*@21) */
  w21  = (w17*w21);
  /* #25: @26 = (@21*@6) */
  w26  = (w21*w6);
  /* #26: @26 = (@26*@13) */
  w26 *= w13;
  /* #27: @7 = (@7-@26) */
  w7 -= w26;
  /* #28: @7 = (@7+@9) */
  w7 += w9;
  /* #29: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  /* #30: @7 = 0.005 */
  w7 = 5.0000000000000001e-03;
  /* #31: @9 = cos(@18) */
  w9 = cos( w18 );
  /* #32: @26 = cos(@3) */
  w26 = cos( w3 );
  /* #33: @27 = (@9*@26) */
  w27  = (w9*w26);
  /* #34: @28 = sin(@1) */
  w28 = sin( w1 );
  /* #35: @29 = sin(@18) */
  w29 = sin( w18 );
  /* #36: @30 = (@28*@29) */
  w30  = (w28*w29);
  /* #37: @31 = sin(@3) */
  w31 = sin( w3 );
  /* #38: @32 = (@30*@31) */
  w32  = (w30*w31);
  /* #39: @27 = (@27+@32) */
  w27 += w32;
  /* #40: @27 = (@7*@27) */
  w27  = (w7*w27);
  /* #41: @32 = (@27*@6) */
  w32  = (w27*w6);
  /* #42: @32 = (@32*@13) */
  w32 *= w13;
  /* #43: @33 = 0.005 */
  w33 = 5.0000000000000001e-03;
  /* #44: @34 = cos(@1) */
  w34 = cos( w1 );
  /* #45: @35 = sin(@3) */
  w35 = sin( w3 );
  /* #46: @36 = (@34*@35) */
  w36  = (w34*w35);
  /* #47: @36 = (@33*@36) */
  w36  = (w33*w36);
  /* #48: @37 = (@36*@6) */
  w37  = (w36*w6);
  /* #49: @37 = (@37*@12) */
  w37 *= w12;
  /* #50: @32 = (@32+@37) */
  w32 += w37;
  /* #51: @32 = (@32+@10) */
  w32 += w10;
  /* #52: output[0][1] = @32 */
  if (res[0]) res[0][1] = w32;
  /* #53: @32 = 0.005 */
  w32 = 5.0000000000000001e-03;
  /* #54: @10 = cos(@1) */
  w10 = cos( w1 );
  /* #55: @37 = sin(@18) */
  w37 = sin( w18 );
  /* #56: @38 = (@10*@37) */
  w38  = (w10*w37);
  /* #57: @38 = (@32*@38) */
  w38  = (w32*w38);
  /* #58: @39 = (@38*@6) */
  w39  = (w38*w6);
  /* #59: @39 = (@39*@13) */
  w39 *= w13;
  /* #60: @40 = 0.005 */
  w40 = 5.0000000000000001e-03;
  /* #61: @41 = sin(@1) */
  w41 = sin( w1 );
  /* #62: @41 = (@40*@41) */
  w41  = (w40*w41);
  /* #63: @42 = (@41*@6) */
  w42  = (w41*w6);
  /* #64: @42 = (@42*@12) */
  w42 *= w12;
  /* #65: @39 = (@39-@42) */
  w39 -= w42;
  /* #66: @39 = (@39+@11) */
  w39 += w11;
  /* #67: output[0][2] = @39 */
  if (res[0]) res[0][2] = w39;
  /* #68: @39 = sin(@18) */
  w39 = sin( w18 );
  /* #69: @11 = cos(@1) */
  w11 = cos( w1 );
  /* #70: @42 = (@6*@14) */
  w42  = (w6*w14);
  /* #71: @43 = (@11*@42) */
  w43  = (w11*w42);
  /* #72: @39 = (@39*@43) */
  w39 *= w43;
  /* #73: @39 = (-@39) */
  w39 = (- w39 );
  /* #74: @43 = 3.07125 */
  w43 = 3.0712530712530715e+00;
  /* #75: @43 = (@43*@15) */
  w43 *= w15;
  /* #76: @39 = (@39-@43) */
  w39 -= w43;
  /* #77: @15 = cos(@18) */
  w15 = cos( w18 );
  /* #78: @44 = input[0][5] */
  w44 = arg[0] ? arg[0][5] : 0;
  /* #79: @45 = (@44*@13) */
  w45  = (w44*w13);
  /* #80: @46 = (@6*@45) */
  w46  = (w6*w45);
  /* #81: @32 = (@32*@46) */
  w32 *= w46;
  /* #82: @10 = (@10*@32) */
  w10 *= w32;
  /* #83: @15 = (@15*@10) */
  w15 *= w10;
  /* #84: @39 = (@39+@15) */
  w39 += w15;
  /* #85: @15 = cos(@18) */
  w15 = cos( w18 );
  /* #86: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #87: @46 = (@10*@13) */
  w46  = (w10*w13);
  /* #88: @47 = (@6*@46) */
  w47  = (w6*w46);
  /* #89: @7 = (@7*@47) */
  w7 *= w47;
  /* #90: @31 = (@31*@7) */
  w31 *= w7;
  /* #91: @28 = (@28*@31) */
  w28 *= w31;
  /* #92: @15 = (@15*@28) */
  w15 *= w28;
  /* #93: @39 = (@39+@15) */
  w39 += w15;
  /* #94: @15 = sin(@18) */
  w15 = sin( w18 );
  /* #95: @26 = (@26*@7) */
  w26 *= w7;
  /* #96: @15 = (@15*@26) */
  w15 *= w26;
  /* #97: @39 = (@39-@15) */
  w39 -= w15;
  /* #98: @15 = cos(@18) */
  w15 = cos( w18 );
  /* #99: @26 = input[0][3] */
  w26 = arg[0] ? arg[0][3] : 0;
  /* #100: @28 = (@26*@13) */
  w28  = (w26*w13);
  /* #101: @47 = (@6*@28) */
  w47  = (w6*w28);
  /* #102: @17 = (@17*@47) */
  w17 *= w47;
  /* #103: @24 = (@24*@17) */
  w24 *= w17;
  /* #104: @15 = (@15*@24) */
  w15 *= w24;
  /* #105: @39 = (@39+@15) */
  w39 += w15;
  /* #106: @15 = sin(@18) */
  w15 = sin( w18 );
  /* #107: @20 = (@20*@17) */
  w20 *= w17;
  /* #108: @15 = (@15*@20) */
  w15 *= w20;
  /* #109: @39 = (@39+@15) */
  w39 += w15;
  /* #110: @15 = cos(@18) */
  w15 = cos( w18 );
  /* #111: @20 = cos(@3) */
  w20 = cos( w3 );
  /* #112: @24 = (@6*@13) */
  w24  = (w6*w13);
  /* #113: @47 = (@20*@24) */
  w47  = (w20*w24);
  /* #114: @15 = (@15*@47) */
  w15 *= w47;
  /* #115: @39 = (@39-@15) */
  w39 -= w15;
  /* #116: @15 = sin(@18) */
  w15 = sin( w18 );
  /* #117: @47 = sin(@1) */
  w47 = sin( w1 );
  /* #118: @48 = sin(@3) */
  w48 = sin( w3 );
  /* #119: @49 = (@48*@24) */
  w49  = (w48*w24);
  /* #120: @50 = (@47*@49) */
  w50  = (w47*w49);
  /* #121: @15 = (@15*@50) */
  w15 *= w50;
  /* #122: @39 = (@39-@15) */
  w39 -= w15;
  /* #123: @15 = cos(@18) */
  w15 = cos( w18 );
  /* #124: @50 = sin(@3) */
  w50 = sin( w3 );
  /* #125: @51 = (@6*@12) */
  w51  = (w6*w12);
  /* #126: @52 = (@50*@51) */
  w52  = (w50*w51);
  /* #127: @15 = (@15*@52) */
  w15 *= w52;
  /* #128: @39 = (@39+@15) */
  w39 += w15;
  /* #129: @15 = sin(@18) */
  w15 = sin( w18 );
  /* #130: @52 = cos(@3) */
  w52 = cos( w3 );
  /* #131: @53 = sin(@1) */
  w53 = sin( w1 );
  /* #132: @54 = (@53*@51) */
  w54  = (w53*w51);
  /* #133: @55 = (@52*@54) */
  w55  = (w52*w54);
  /* #134: @15 = (@15*@55) */
  w15 *= w55;
  /* #135: @39 = (@39-@15) */
  w39 -= w15;
  /* #136: output[0][3] = @39 */
  if (res[0]) res[0][3] = w39;
  /* #137: @39 = sin(@1) */
  w39 = sin( w1 );
  /* #138: @15 = cos(@18) */
  w15 = cos( w18 );
  /* #139: @42 = (@15*@42) */
  w42  = (w15*w42);
  /* #140: @39 = (@39*@42) */
  w39 *= w42;
  /* #141: @39 = (-@39) */
  w39 = (- w39 );
  /* #142: @42 = 3.07787 */
  w42 = 3.0778701138811941e+00;
  /* #143: @42 = (@42*@16) */
  w42 *= w16;
  /* #144: @39 = (@39-@42) */
  w39 -= w42;
  /* #145: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #146: @37 = (@37*@32) */
  w37 *= w32;
  /* #147: @16 = (@16*@37) */
  w16 *= w37;
  /* #148: @39 = (@39-@16) */
  w39 -= w16;
  /* #149: @16 = cos(@1) */
  w16 = cos( w1 );
  /* #150: @29 = (@29*@31) */
  w29 *= w31;
  /* #151: @16 = (@16*@29) */
  w16 *= w29;
  /* #152: @39 = (@39+@16) */
  w39 += w16;
  /* #153: @16 = cos(@1) */
  w16 = cos( w1 );
  /* #154: @25 = (@25*@17) */
  w25 *= w17;
  /* #155: @22 = (@22*@25) */
  w22 *= w25;
  /* #156: @16 = (@16*@22) */
  w16 *= w22;
  /* #157: @39 = (@39+@16) */
  w39 += w16;
  /* #158: @16 = cos(@1) */
  w16 = cos( w1 );
  /* #159: @22 = cos(@18) */
  w22 = cos( w18 );
  /* #160: @49 = (@22*@49) */
  w49  = (w22*w49);
  /* #161: @16 = (@16*@49) */
  w16 *= w49;
  /* #162: @39 = (@39+@16) */
  w39 += w16;
  /* #163: @16 = cos(@1) */
  w16 = cos( w1 );
  /* #164: @44 = (@44*@12) */
  w44 *= w12;
  /* #165: @49 = (@6*@44) */
  w49  = (w6*w44);
  /* #166: @40 = (@40*@49) */
  w40 *= w49;
  /* #167: @16 = (@16*@40) */
  w16 *= w40;
  /* #168: @39 = (@39-@16) */
  w39 -= w16;
  /* #169: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #170: @10 = (@10*@12) */
  w10 *= w12;
  /* #171: @40 = (@6*@10) */
  w40  = (w6*w10);
  /* #172: @33 = (@33*@40) */
  w33 *= w40;
  /* #173: @35 = (@35*@33) */
  w35 *= w33;
  /* #174: @16 = (@16*@35) */
  w16 *= w35;
  /* #175: @39 = (@39-@16) */
  w39 -= w16;
  /* #176: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #177: @26 = (@26*@12) */
  w26 *= w12;
  /* #178: @6 = (@6*@26) */
  w6 *= w26;
  /* #179: @0 = (@0*@6) */
  w0 *= w6;
  /* #180: @4 = (@4*@0) */
  w4 *= w0;
  /* #181: @16 = (@16*@4) */
  w16 *= w4;
  /* #182: @39 = (@39+@16) */
  w39 += w16;
  /* #183: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #184: @16 = cos(@18) */
  w16 = cos( w18 );
  /* #185: @52 = (@16*@52) */
  w52  = (w16*w52);
  /* #186: @4 = (@52*@51) */
  w4  = (w52*w51);
  /* #187: @1 = (@1*@4) */
  w1 *= w4;
  /* #188: @39 = (@39+@1) */
  w39 += w1;
  /* #189: output[0][4] = @39 */
  if (res[0]) res[0][4] = w39;
  /* #190: @39 = cos(@3) */
  w39 = cos( w3 );
  /* #191: @30 = (@30*@7) */
  w30 *= w7;
  /* #192: @39 = (@39*@30) */
  w39 *= w30;
  /* #193: @30 = sin(@3) */
  w30 = sin( w3 );
  /* #194: @9 = (@9*@7) */
  w9 *= w7;
  /* #195: @30 = (@30*@9) */
  w30 *= w9;
  /* #196: @39 = (@39-@30) */
  w39 -= w30;
  /* #197: @30 = sin(@3) */
  w30 = sin( w3 );
  /* #198: @23 = (@23*@25) */
  w23 *= w25;
  /* #199: @30 = (@30*@23) */
  w30 *= w23;
  /* #200: @39 = (@39-@30) */
  w39 -= w30;
  /* #201: @30 = cos(@3) */
  w30 = cos( w3 );
  /* #202: @19 = (@19*@17) */
  w19 *= w17;
  /* #203: @30 = (@30*@19) */
  w30 *= w19;
  /* #204: @39 = (@39-@30) */
  w39 -= w30;
  /* #205: @30 = sin(@3) */
  w30 = sin( w3 );
  /* #206: @19 = sin(@18) */
  w19 = sin( w18 );
  /* #207: @17 = (@19*@24) */
  w17  = (w19*w24);
  /* #208: @30 = (@30*@17) */
  w30 *= w17;
  /* #209: @39 = (@39+@30) */
  w39 += w30;
  /* #210: @30 = cos(@3) */
  w30 = cos( w3 );
  /* #211: @22 = (@22*@47) */
  w22 *= w47;
  /* #212: @24 = (@22*@24) */
  w24  = (w22*w24);
  /* #213: @30 = (@30*@24) */
  w30 *= w24;
  /* #214: @39 = (@39+@30) */
  w39 += w30;
  /* #215: @30 = cos(@3) */
  w30 = cos( w3 );
  /* #216: @34 = (@34*@33) */
  w34 *= w33;
  /* #217: @30 = (@30*@34) */
  w30 *= w34;
  /* #218: @39 = (@39+@30) */
  w39 += w30;
  /* #219: @30 = sin(@3) */
  w30 = sin( w3 );
  /* #220: @2 = (@2*@0) */
  w2 *= w0;
  /* #221: @30 = (@30*@2) */
  w30 *= w2;
  /* #222: @39 = (@39+@30) */
  w39 += w30;
  /* #223: @30 = cos(@3) */
  w30 = cos( w3 );
  /* #224: @18 = sin(@18) */
  w18 = sin( w18 );
  /* #225: @51 = (@18*@51) */
  w51  = (w18*w51);
  /* #226: @30 = (@30*@51) */
  w30 *= w51;
  /* #227: @39 = (@39+@30) */
  w39 += w30;
  /* #228: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #229: @16 = (@16*@54) */
  w16 *= w54;
  /* #230: @3 = (@3*@16) */
  w3 *= w16;
  /* #231: @39 = (@39-@3) */
  w39 -= w3;
  /* #232: output[0][5] = @39 */
  if (res[0]) res[0][5] = w39;
  /* #233: @39 = 1.0234 */
  w39 = 1.0234000000000001e+00;
  /* #234: @39 = (@39*@43) */
  w39 *= w43;
  /* #235: output[0][6] = @39 */
  if (res[0]) res[0][6] = w39;
  /* #236: @39 = 1.0266 */
  w39 = 1.0266000000000000e+00;
  /* #237: @39 = (@39*@42) */
  w39 *= w42;
  /* #238: output[0][7] = @39 */
  if (res[0]) res[0][7] = w39;
  /* #239: @11 = (@11*@15) */
  w11 *= w15;
  /* #240: @11 = (@11*@14) */
  w11 *= w14;
  /* #241: @38 = (@38*@45) */
  w38 *= w45;
  /* #242: @11 = (@11+@38) */
  w11 += w38;
  /* #243: @27 = (@27*@46) */
  w27 *= w46;
  /* #244: @11 = (@11+@27) */
  w11 += w27;
  /* #245: @21 = (@21*@28) */
  w21 *= w28;
  /* #246: @11 = (@11-@21) */
  w11 -= w21;
  /* #247: @22 = (@22*@48) */
  w22 *= w48;
  /* #248: @20 = (@20*@19) */
  w20 *= w19;
  /* #249: @22 = (@22-@20) */
  w22 -= w20;
  /* #250: @22 = (@22*@13) */
  w22 *= w13;
  /* #251: @11 = (@11+@22) */
  w11 += w22;
  /* #252: @41 = (@41*@44) */
  w41 *= w44;
  /* #253: @11 = (@11-@41) */
  w11 -= w41;
  /* #254: @36 = (@36*@10) */
  w36 *= w10;
  /* #255: @11 = (@11+@36) */
  w11 += w36;
  /* #256: @5 = (@5*@26) */
  w5 *= w26;
  /* #257: @11 = (@11-@5) */
  w11 -= w5;
  /* #258: @52 = (@52*@53) */
  w52 *= w53;
  /* #259: @18 = (@18*@50) */
  w18 *= w50;
  /* #260: @52 = (@52+@18) */
  w52 += w18;
  /* #261: @52 = (@52*@12) */
  w52 *= w12;
  /* #262: @11 = (@11+@52) */
  w11 += w52;
  /* #263: output[0][8] = @11 */
  if (res[0]) res[0][8] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 64;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
