/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {12, 1, 0, 9, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* mav_nmpc_tracker_model_expl_vde_adj:(i0[9],i1[9],i2[3],i3[])->(o0[12x1,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 9, w0);
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8, NULL} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  w4 = w0[3];
  w5 = w0[4];
  w6 = w0[5];
  w7 = w0[6];
  w8 = w0[7];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #5: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #6: @2 = sin(@3) */
  w2 = sin( w3 );
  /* #7: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #8: @9 = cos(@1) */
  w9 = cos( w1 );
  /* #9: @10 = input[2][2] */
  w10 = arg[2] ? arg[2][2] : 0;
  /* #10: @11 = 0.641026 */
  w11 = 6.4102564102564097e-01;
  /* #11: @11 = (@11*@6) */
  w11 *= w6;
  /* #12: @6 = (@10*@11) */
  w6  = (w10*w11);
  /* #13: @12 = (@9*@6) */
  w12  = (w9*w6);
  /* #14: @2 = (@2*@12) */
  w2 *= w12;
  /* #15: @2 = (-@2) */
  w2 = (- w2 );
  /* #16: @12 = 3.89105 */
  w12 = 3.8910505836575875e+00;
  /* #17: @12 = (@12*@7) */
  w12 *= w7;
  /* #18: @2 = (@2-@12) */
  w2 -= w12;
  /* #19: @7 = cos(@3) */
  w7 = cos( w3 );
  /* #20: @13 = input[0][8] */
  w13 = arg[0] ? arg[0][8] : 0;
  /* #21: @14 = cos(@13) */
  w14 = cos( w13 );
  /* #22: @15 = 0.641026 */
  w15 = 6.4102564102564097e-01;
  /* #23: @15 = (@15*@5) */
  w15 *= w5;
  /* #24: @5 = (@10*@15) */
  w5  = (w10*w15);
  /* #25: @16 = (@14*@5) */
  w16  = (w14*w5);
  /* #26: @7 = (@7*@16) */
  w7 *= w16;
  /* #27: @2 = (@2-@7) */
  w2 -= w7;
  /* #28: @7 = sin(@3) */
  w7 = sin( w3 );
  /* #29: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #30: @17 = sin(@13) */
  w17 = sin( w13 );
  /* #31: @18 = (@17*@5) */
  w18  = (w17*w5);
  /* #32: @19 = (@16*@18) */
  w19  = (w16*w18);
  /* #33: @7 = (@7*@19) */
  w7 *= w19;
  /* #34: @2 = (@2-@7) */
  w2 -= w7;
  /* #35: @7 = cos(@3) */
  w7 = cos( w3 );
  /* #36: @19 = sin(@13) */
  w19 = sin( w13 );
  /* #37: @20 = 0.641026 */
  w20 = 6.4102564102564097e-01;
  /* #38: @20 = (@20*@4) */
  w20 *= w4;
  /* #39: @10 = (@10*@20) */
  w10 *= w20;
  /* #40: @4 = (@19*@10) */
  w4  = (w19*w10);
  /* #41: @7 = (@7*@4) */
  w7 *= w4;
  /* #42: @2 = (@2+@7) */
  w2 += w7;
  /* #43: @7 = sin(@3) */
  w7 = sin( w3 );
  /* #44: @4 = cos(@13) */
  w4 = cos( w13 );
  /* #45: @21 = sin(@1) */
  w21 = sin( w1 );
  /* #46: @22 = (@21*@10) */
  w22  = (w21*w10);
  /* #47: @23 = (@4*@22) */
  w23  = (w4*w22);
  /* #48: @7 = (@7*@23) */
  w7 *= w23;
  /* #49: @2 = (@2-@7) */
  w2 -= w7;
  /* #50: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #51: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #52: @7 = cos(@3) */
  w7 = cos( w3 );
  /* #53: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #54: @2 = (@2*@6) */
  w2 *= w6;
  /* #55: @2 = (-@2) */
  w2 = (- w2 );
  /* #56: @6 = 3.861 */
  w6 = 3.8610038610038608e+00;
  /* #57: @6 = (@6*@8) */
  w6 *= w8;
  /* #58: @2 = (@2-@6) */
  w2 -= w6;
  /* #59: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #60: @23 = cos(@3) */
  w23 = cos( w3 );
  /* #61: @18 = (@23*@18) */
  w18  = (w23*w18);
  /* #62: @8 = (@8*@18) */
  w8 *= w18;
  /* #63: @2 = (@2+@8) */
  w2 += w8;
  /* #64: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #65: @8 = cos(@3) */
  w8 = cos( w3 );
  /* #66: @4 = (@8*@4) */
  w4  = (w8*w4);
  /* #67: @18 = (@4*@10) */
  w18  = (w4*w10);
  /* #68: @1 = (@1*@18) */
  w1 *= w18;
  /* #69: @2 = (@2+@1) */
  w2 += w1;
  /* #70: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #71: @2 = sin(@13) */
  w2 = sin( w13 );
  /* #72: @1 = sin(@3) */
  w1 = sin( w3 );
  /* #73: @18 = (@1*@5) */
  w18  = (w1*w5);
  /* #74: @2 = (@2*@18) */
  w2 *= w18;
  /* #75: @18 = cos(@13) */
  w18 = cos( w13 );
  /* #76: @23 = (@23*@16) */
  w23 *= w16;
  /* #77: @5 = (@23*@5) */
  w5  = (w23*w5);
  /* #78: @18 = (@18*@5) */
  w18 *= w5;
  /* #79: @2 = (@2+@18) */
  w2 += w18;
  /* #80: @18 = cos(@13) */
  w18 = cos( w13 );
  /* #81: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #82: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #83: @18 = (@18*@10) */
  w18 *= w10;
  /* #84: @2 = (@2+@18) */
  w2 += w18;
  /* #85: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #86: @8 = (@8*@22) */
  w8 *= w22;
  /* #87: @13 = (@13*@8) */
  w13 *= w8;
  /* #88: @2 = (@2-@13) */
  w2 -= w13;
  /* #89: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #90: @2 = 0.75 */
  w2 = 7.5000000000000000e-01;
  /* #91: @2 = (@2*@12) */
  w2 *= w12;
  /* #92: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #93: @2 = 0.78 */
  w2 = 7.8000000000000003e-01;
  /* #94: @2 = (@2*@6) */
  w2 *= w6;
  /* #95: output[0][7] = @2 */
  if (res[0]) res[0][7] = w2;
  /* #96: @9 = (@9*@7) */
  w9 *= w7;
  /* #97: @9 = (@9*@11) */
  w9 *= w11;
  /* #98: @23 = (@23*@17) */
  w23 *= w17;
  /* #99: @14 = (@14*@1) */
  w14 *= w1;
  /* #100: @23 = (@23-@14) */
  w23 -= w14;
  /* #101: @23 = (@23*@15) */
  w23 *= w15;
  /* #102: @9 = (@9+@23) */
  w9 += w23;
  /* #103: @4 = (@4*@21) */
  w4 *= w21;
  /* #104: @3 = (@3*@19) */
  w3 *= w19;
  /* #105: @4 = (@4+@3) */
  w4 += w3;
  /* #106: @4 = (@4*@20) */
  w4 *= w20;
  /* #107: @9 = (@9+@4) */
  w9 += w4;
  /* #108: output[0][8] = @9 */
  if (res[0]) res[0][8] = w9;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 32;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
