/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* mav_nmpc_tracker_model_expl_ode_fun:(i0[9],i1[3],i2[])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #7: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #8: @2 = input[0][8] */
  w2 = arg[0] ? arg[0][8] : 0;
  /* #9: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #10: @1 = (@1*@3) */
  w1 *= w3;
  /* #11: @3 = input[0][7] */
  w3 = arg[0] ? arg[0][7] : 0;
  /* #12: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #13: @1 = (@1*@4) */
  w1 *= w4;
  /* #14: @4 = sin(@0) */
  w4 = sin( w0 );
  /* #15: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #16: @4 = (@4*@5) */
  w4 *= w5;
  /* #17: @1 = (@1+@4) */
  w1 += w4;
  /* #18: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #19: @1 = (@1*@4) */
  w1 *= w4;
  /* #20: @5 = 1.56 */
  w5 = 1.5600000000000001e+00;
  /* #21: @1 = (@1/@5) */
  w1 /= w5;
  /* #22: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #23: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #24: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #25: @1 = (@1*@5) */
  w1 *= w5;
  /* #26: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #27: @1 = (@1*@5) */
  w1 *= w5;
  /* #28: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #29: @5 = sin(@0) */
  w5 = sin( w0 );
  /* #30: @2 = (@2*@5) */
  w2 *= w5;
  /* #31: @1 = (@1-@2) */
  w1 -= w2;
  /* #32: @1 = (@1*@4) */
  w1 *= w4;
  /* #33: @2 = 1.56 */
  w2 = 1.5600000000000001e+00;
  /* #34: @1 = (@1/@2) */
  w1 /= w2;
  /* #35: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #36: @1 = -9.8066 */
  w1 = -9.8065999999999995e+00;
  /* #37: @2 = cos(@3) */
  w2 = cos( w3 );
  /* #38: @5 = cos(@0) */
  w5 = cos( w0 );
  /* #39: @2 = (@2*@5) */
  w2 *= w5;
  /* #40: @2 = (@2*@4) */
  w2 *= w4;
  /* #41: @4 = 1.56 */
  w4 = 1.5600000000000001e+00;
  /* #42: @2 = (@2/@4) */
  w2 /= w4;
  /* #43: @1 = (@1+@2) */
  w1 += w2;
  /* #44: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #45: @1 = 0.75 */
  w1 = 7.5000000000000000e-01;
  /* #46: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #47: @1 = (@1*@2) */
  w1 *= w2;
  /* #48: @1 = (@1-@0) */
  w1 -= w0;
  /* #49: @0 = 0.257 */
  w0 = 2.5700000000000001e-01;
  /* #50: @1 = (@1/@0) */
  w1 /= w0;
  /* #51: output[0][6] = @1 */
  if (res[0]) res[0][6] = w1;
  /* #52: @1 = 0.78 */
  w1 = 7.8000000000000003e-01;
  /* #53: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #54: @1 = (@1*@0) */
  w1 *= w0;
  /* #55: @1 = (@1-@3) */
  w1 -= w3;
  /* #56: @3 = 0.259 */
  w3 = 2.5900000000000001e-01;
  /* #57: @1 = (@1/@3) */
  w1 /= w3;
  /* #58: output[0][7] = @1 */
  if (res[0]) res[0][7] = w1;
  /* #59: @1 = 0 */
  w1 = 0.;
  /* #60: output[0][8] = @1 */
  if (res[0]) res[0][8] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
